name: Update .luacheckrc

on:
  workflow_dispatch:
  schedule:
    - cron: 0 1 * * *

jobs:
  generate:
    runs-on: ubuntu-latest
    name: generate new .luacheckrc
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Generate new .luacheckrc
        uses: bmos/action-generate-luacheckrc@master

      - name: Create pull request
        uses: peter-evans/create-pull-request@v3
        with:
          title: Update .luacheckrc
          commit-message: "test: update .luacheckrc"
          branch: update-luacheckrc
          delete-branch: true
