name: Update .luacheckrc

on:
  push:
    paths:
      - '.luacheckrc_header'
      - '.github/workflows/main.yml'
  schedule:
    - cron: 0 0 * * *
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    name: generate new .luacheckrc
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    # Rulesets
    - name: Clone FG-Unofficial-Developers-Guild/CoreRPG
      uses: actions/checkout@v3
      with:
        repository: FG-Unofficial-Developers-Guild/CoreRPG
        path: .fg/rulesets/CoreRPG
        fetch-depth: 0
        token: ${{ secrets.ACTIONS }}

    - name: Clone FG-Unofficial-Developers-Guild/2E
      uses: actions/checkout@v3
      with:
        repository: FG-Unofficial-Developers-Guild/2E
        path: .fg/rulesets/DND2E
        fetch-depth: 0
        token: ${{ secrets.ACTIONS }}

    - name: Clone FG-Unofficial-Developers-Guild/3.5E
      uses: actions/checkout@v3
      with:
        repository: FG-Unofficial-Developers-Guild/3.5E
        path: .fg/rulesets/DND35E
        fetch-depth: 0
        token: ${{ secrets.ACTIONS }}

    - name: Clone FG-Unofficial-Developers-Guild/4e
      uses: actions/checkout@v3
      with:
        repository: FG-Unofficial-Developers-Guild/4e
        path: .fg/rulesets/DND4E
        fetch-depth: 0
        token: ${{ secrets.ACTIONS }}

    - name: Clone FG-Unofficial-Developers-Guild/5e
      uses: actions/checkout@v3
      with:
        repository: FG-Unofficial-Developers-Guild/5e
        path: .fg/rulesets/DND5E
        fetch-depth: 0
        token: ${{ secrets.ACTIONS }}

    - name: Clone FG-Unofficial-Developers-Guild/PFRPG
      uses: actions/checkout@v3
      with:
        repository: FG-Unofficial-Developers-Guild/PFRPG
        path: .fg/rulesets/PFRPG
        fetch-depth: 0
        token: ${{ secrets.ACTIONS }}

    - name: Clone FG-Unofficial-Developers-Guild/PFRPG2
      uses: actions/checkout@v3
      with:
        repository: FG-Unofficial-Developers-Guild/PFRPG2
        path: .fg/rulesets/PFRPG2
        fetch-depth: 0
        token: ${{ secrets.ACTIONS }}

    - name: Clone FG-Unofficial-Developers-Guild/SFRPG
      uses: actions/checkout@v3
      with:
        repository: FG-Unofficial-Developers-Guild/SFRPG
        path: .fg/rulesets/SFRPG
        fetch-depth: 0
        token: ${{ secrets.ACTIONS }}

    # Extensions
    - name: Clone rhagelstrom/Exhausted
      uses: actions/checkout@v3
      with:
        repository: rhagelstrom/Exhausted
        path: .fg/extensions/Exhausted
        fetch-depth: 0
        token: ${{ secrets.ACTIONS }}

    - name: Clone rhagelstrom/BetterCombatEffects
      uses: actions/checkout@v3
      with:
        repository: rhagelstrom/BetterCombatEffects
        path: .fg/extensions/BetterCombatEffects
        fetch-depth: 0
        token: ${{ secrets.ACTIONS }}

    - name: Clone rhagelstrom/BetterCombatEffects
      uses: actions/checkout@v3
      with:
        repository: rhagelstrom/BetterCombatEffectsGold
        path: .fg/extensions/BetterCombatEffectsGold
        fetch-depth: 0
        token: ${{ secrets.ACTIONS }}

    - name: Clone rhagelstrom/Fatigued
      uses: actions/checkout@v3
      with:
        repository: rhagelstrom/Fatigued
        path: .fg/extensions/Fatigued
        fetch-depth: 0
        token: ${{ secrets.ACTIONS }}

    - name: Clone rhagelstrom/Exhausted
      uses: actions/checkout@v3
      with:
        repository: rhagelstrom/Exhausted
        path: .fg/extensions/Exhausted
        fetch-depth: 0
        token: ${{ secrets.ACTIONS }}

    - name: Clone rhagelstrom/Contaminated
      uses: actions/checkout@v3
      with:
        repository: rhagelstrom/Contaminated
        path: .fg/extensions/Contaminated
        fetch-depth: 0
        token: ${{ secrets.ACTIONS }}

    - name: Clone rhagelstrom/ArcaneWard
      uses: actions/checkout@v3
      with:
        repository: rhagelstrom/ArcaneWard
        path: .fg/extensions/ArcaneWard
        fetch-depth: 0
        token: ${{ secrets.ACTIONS }}

    - name: Clone rhagelstrom/FranklyNot
      uses: actions/checkout@v3
      with:
        repository: rhagelstrom/FranklyNot
        path: .fg/extensions/FranklyNot
        fetch-depth: 0
        token: ${{ secrets.ACTIONS }}

    - name: Clone rhagelstrom/ChatAestheticsConfigurator
      uses: actions/checkout@v3
      with:
        repository: rhagelstrom/ChatAestheticsConfigurator
        path: .fg/extensions/ChatAestheticsConfigurator
        fetch-depth: 0
        token: ${{ secrets.ACTIONS }}

    - name: Clone rhagelstrom/EffectiveInitiative
      uses: actions/checkout@v3
      with:
        repository: rhagelstrom/EffectiveInitiative
        path: .fg/extensions/EffectiveInitiative
        fetch-depth: 0
        token: ${{ secrets.ACTIONS }}

    - name: Clone rhagelstrom/PowerUp
      uses: actions/checkout@v3
      with:
        repository: rhagelstrom/PowerUp
        path: .fg/extensions/PowerUp
        fetch-depth: 0
        token: ${{ secrets.ACTIONS }}

    # Processing 
    - name: Generate new .luacheckrc
      uses: FG-Unofficial-Developers-Guild/action-generate-luacheckrc@main
      with:
        std: '+dnd2e+dnd35e+dnd4e+dnd5e+pfrpg+pfrpg2'

    - name: Create pull request
      uses: peter-evans/create-pull-request@v4
      with:
        title: Update .luacheckrc
        commit-message: "test: update .luacheckrc"
        branch: update-luacheckrc
        delete-branch: true
